# Generated by Django 6.0 on 2025-12-04 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flight_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='gender',
            field=models.CharField(default='MALE', max_length=10),
        ),
    ]
